import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "./components/navbar";
// import Footer from "./components/footer";
// import Toup from "./components/toup";
// import NextTopLoader from "nextjs-toploader";

// Font imports
import { Montserrat, Lato } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Guru Mantra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${lato.variable}`}>
      <body className="flex flex-col min-h-screen font-body">
        {/* <NextTopLoader speed={1000} color="#2196f3" /> */}
        <header>
          <div>
            {/* <Navbar /> */}
          </div>
        </header>

        {/* Content section with flex-grow to push footer down */}
        {/* <main className="pt-20 px-4 sm:px-6 md:px-8 lg:px-12 xl:px-20">{children}</main> */}
        <main>{children}</main>

        {/* <Toup /> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
